---
title: "Midterm"
author: "Jeffrey Zhuohui Liang"
date: "3/7/2021"
output: pdf_document
---

```{r setup, include=FALSE}
set.seed(123123)
library(reticulate)
library(tidyverse)
library(caret)
library(glmnet)
library(pls)
library(splines)
library(mgcv)
library(pdp)
library(earth)
library(doParallel)
library(patchwork)

knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = 8,
  message = F,
  echo = T,
  warning = F,
  cache = T
)
theme_set(theme_minimal() + theme(
  legend.position = "bottom",
  plot.title = element_text(hjust = 0.5)
))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)


scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```



\section{Method}

```{r load_data,echo=F}
hrt_data =
  tibble(
    location = c("cle", "swi", "va", "hun"),
    file =
      c(
        "./data/processed.cleveland.data",
        "./data/processed.switzerland.data",
        "./data/processed.va.data",
        "./data/processed.hungarian.data"
      )
  ) %>%
  mutate(location = as.factor(location),
         data = map(file,
                    ~ read_csv(here::here(.x), col_names = F,
                               col_types = "dddddddddddddd"))) %>% 
  unnest(data)

# change column's name
colnames(hrt_data)[3:16] = c(
  "Age",
  "Sex",
  "Chest_Pain_Type",
  "Resting_Blood_Pressure",
  "Serum_Cholesterol",
  "Fasting_Blood_Sugar",
  "Resting_ECG",
  "Max_Heart_Rate_Achieved",
  "Exercise_Induced_Angina",
  "ST_Depression_Exercise",
  "Peak_Exercise_ST_Segment",
  "Num_Major_Vessels_Flouro",
  "Thalassemia",
  "Diagnosis_Heart_Disease"
)

hrt_data  = hrt_data %>%
  janitor::clean_names() %>%
  select(-file) %>%
  mutate(
    sex = case_when(sex == 0 ~ "female",
                    sex == 1 ~ "male"),
    chest_pain_type = case_when(
      chest_pain_type == 1 ~ "typical angina",
      chest_pain_type == 2 ~ "atypical angina",
      chest_pain_type == 3 ~ "non-angina pain",
      chest_pain_type == 4 ~ "asymptomatic angina"
    ),
    fasting_blood_sugar =
      case_when(
        fasting_blood_sugar == 0 ~ "fasting blood sugar <= 120 mg/dl",
        fasting_blood_sugar == 1 ~ "fasting blood sugar > 120 mg/dl"
      ),
    resting_ecg = case_when(
      resting_ecg == 0 ~ "normal",
      resting_ecg == 1 ~ "ST-T wave abnormality",
      resting_ecg == 2 ~ "left ventricle hyperthrophy"
    ),
    exercise_induced_angina = 
      case_when(
       exercise_induced_angina ==  0 ~ 'no',
       exercise_induced_angina == 1 ~ "yes"
      ),
    peak_exercise_st_segment =
      case_when(
        peak_exercise_st_segment == 1 ~ "Up-sloaping",
        peak_exercise_st_segment == 2 ~ "Flat",
        peak_exercise_st_segment == 3 ~ "Down-sloaping"
      ),
    thalassemia =
      case_when(
        thalassemia == 3 ~ "normal",
        thalassemia  == 6 ~ "fixed defect",
        thalassemia == 7 ~ "reversible defect"
      ),
    diagnosis_heart_disease = 
      case_when(
        diagnosis_heart_disease == 0 ~ "absense",
        diagnosis_heart_disease >0 ~"present"
      ),
    across(where(is.character),as.factor)
  ) %>% 
  relocate(diagnosis_heart_disease)

skimr::skim_without_charts(hrt_data)
```

```{r data_preprocess}
# split into training set
train_index = createDataPartition(hrt_data$diagnosis_heart_disease,p=0.8,list = F)

Y_tr = hrt_data$diagnosis_heart_disease[train_index]

Y_ts = hrt_data$diagnosis_heart_disease[-train_index]

options(na.action = "na.pass")
X_tr = model.matrix(diagnosis_heart_disease ~., hrt_data,na.action = "na.pass")[train_index,-1]

X_ts = model.matrix(diagnosis_heart_disease ~., hrt_data,na.action = "na.pass")[-train_index,-1]

TRC = caret::trainControl(method = "repeatedcv",repeats=5,
                          summaryFunction = twoClassSummary,
                          classProbs = T)

PPS = c("knnImpute", "center", "scale")
```
# Modeling


```{r logistic,cache=T}
set.seed(123123)
cl = parallel::makePSOCKcluster(5)
doParallel::registerDoParallel(cl)

logistic_model =
  train(
    X_tr,
    Y_tr,
    method = "glmnet",
    tuneGrid = expand.grid(alpha = seq(0,1,length=6),
                           lambda = exp(seq(
                             6, to = -6, length = 50
                           ))),
    family = "binomial",
    preProcess = PPS,
    metric = "ROC",
    trControl = TRC
  )

stopCluster(cl)

p_logistics =
  ggplot(logistic_model) +
  scale_x_continuous(trans = "log")+
  labs(title = "Lasso Logistics")
```

```{r MARS,cache=T}
set.seed(123123)
cl = parallel::makePSOCKcluster(5)
doParallel::registerDoParallel(cl)

mars_model = 
  train(X_tr,
        Y_tr,
        method = "earth",
        tuneGrid = expand.grid(degree = 1:3,
                               nprune = 5:20),
        preProcess = PPS,
        trControl = TRC,
        metric = "ROC")

stopCluster(cl)

p_mars = ggplot(mars_model) +labs(title ="MARS")
```

```{r knn,cache=T}
set.seed(123123)
cl = parallel::makePSOCKcluster(5)
doParallel::registerDoParallel(cl)

knn_model = 
  train(X_tr,
        Y_tr,
        method = "knn",
        tuneGrid = expand.grid(k = seq(10,60,2)),
        preProcess = PPS,
        trControl = TRC,
        metric = "ROC")

stopCluster(cl)

p_knn = ggplot(knn_model)+labs(title = "KNN")
```

```{r lda,cache=T}
set.seed(123123)
cl = parallel::makePSOCKcluster(5)
doParallel::registerDoParallel(cl)

lda_model =  train(
  X_tr,
  Y_tr,
  method = "lda",
  preProcess = PPS,
  trControl = TRC,
  metric = "ROC"
)

stopCluster(cl)
```

```{r qda,cache=T}
set.seed(123123)
cl = parallel::makePSOCKcluster(5)
doParallel::registerDoParallel(cl)

qda_model =  train(
  X_tr,
  Y_tr,
  method = "qda",
  preProcess = PPS,
  trControl = TRC,
  metric = "ROC"
)

stopCluster(cl)
```

```{r tree,cache=T}
set.seed(123123)
cl = parallel::makePSOCKcluster(5)
doParallel::registerDoParallel(cl)

tree_model =
  train(
    X_tr,
    Y_tr,
    method = "rpart",
    tuneGrid = expand.grid(
      cp = exp(seq(-10,-3,length=50))
    ),
    preProcess = PPS,
    trControl = TRC,
    metric = "ROC"
  )
stopCluster(cl)

ggplot(tree_model,highlight = T)
```

```{r res}
coef(logistic_model$finalModel,logistic_model$bestTune$lambda) %>% 
  as.vector() %>% 
  tibble(term = c("Intercept",colnames(X_tr)),
         coefficient = .) %>% 
  knitr::kable(caption = "Coefficient of Lasso Logistic Regression")

p_mv = vip::vip(mars_model$finalModel) + labs(title = "MARS: Importance of predictor")

p_ll = ggplotify::as.ggplot(~plot_glmnet(logistic_model$finalModel))
p_ll = p_ll + labs(title = "Lasso Logistics Model") +
  xlim(c(0.1,1))+
  ylim(c(0.1,1))

(p_ll | p_mv) / p_tree

p_logistics | (p_mars/p_knn)


```


## Performance comparison

```{r rsmp}
rsmp = resamples(
  list(
    logistic = logistic_model,
    MARS = mars_model,
    knn = knn_model,
    lda = lda_model,
    qda = qda_model
  ),
  metric = c("ROC", "Kappa")
)

summary(rsmp)

bwplot(rsmp,metric = "ROC")
```

```{r ROC}
ROC =
  expand.grid(
    test_X = list(X_ts),
    test_Y = list(Y_ts),
    model = list(logistic_model, mars_model, knn_model, lda_model, qda_model)
  ) %>%
  mutate(
    pred = map2(model, test_X,  ~ predict(.x, newdata = .y, type = "prob")[, 2]),
    roc = map2(test_Y, pred,  ~ pROC::roc(.x, .y))
  ) %>% 
  pull(roc)

auc = c()

for (i in 1:5){
  auc = append(auc,ROC[[i]]$auc[1])
  plot(ROC[[i]],col = i, add = T * (i>1), legacy.axes = T * (i==1))
}

model_name = 
  c("lasso logistic","MARS","KNN","LDA","QDA")

legend("bottomright",
       legend = paste0(model_name,"~",round(auc,3)),col=1:5,lwd=2)
```


